CREATE DATABASE IF NOT EXISTS pdfdb;

USE pdfdb;

CREATE TABLE File (
    FileID INT AUTO_INCREMENT PRIMARY KEY,
    Filename VARCHAR(255) NOT NULL,
    Date DATE NOT NULL,
);
CREATE TABLE Par (
    ParID INT AUTO_INCREMENT PRIMARY KEY,
    FileID INT NOT NULL,
    Title VARCHAR(255) NOT NULL,
    Description TEXT,
    Time TIME,
    FOREIGN KEY (FileID) REFERENCES File(FileID)
);